version = 4
final_space = true

[palette]
  accent = '#F86F03'
  black = '#072541'
  overlay = '#7f3515'
  primary = '#F11A7B'
  secondary = '#f5c2e7'
  white = '#FCF5ED'

[secondary_prompt]
  template = ' '
  foreground = 'p:secondary'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  foreground = 'p:secondary'
  background = 'transparant'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    trailing_diamond = ''
    template = ' {{ .UserName }} {{ .Icon }} '
    foreground = 'p:white'
    background = 'p:primary'
    type = 'os'
    style = 'diamond'

  [[blocks.segments]]
    foreground = 'p:primary'
    type = 'path'
    style = 'plain'

    [blocks.segments.options]
      style = 'full'

  [[blocks.segments]]
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{ if and (.Working.Changed) (.Staging.Changed) }} {{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    foreground = 'p:secondary'
    type = 'git'
    style = 'plain'

    [blocks.segments.options]
      branch_icon = '󰊢 '
      fetch_status = true

      [blocks.segments.options.status_formats]
        Added = '<#94e2d5>  %d</>'
        Deleted = '<#f38ba8>  %d</>'
        Modified = '<#74c7ec>  %d</>'
        Unmerged = '<#f9e2af>  %d</>'
        Untracked = '<#f5e0dc> 󰆢 %d</>'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    template = ' {{ .FormattedMs }} '
    foreground = 'p:primary'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.options]
      style = 'austin'
      threshold = 500

  [[blocks.segments]]
    template = '  '
    foreground = 'p:primary'
    type = 'deno'
    style = 'plain'

  [[blocks.segments]]
    template = ' '
    type = 'php'
    style = 'plain'

  [[blocks.segments]]
    foreground = 'p:primary'
    type = 'time'
    style = 'plain'

    [blocks.segments.options]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    foreground = 'p:primary'
    type = 'text'
    style = 'plain'
