"$schema"   = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version	    = 3
final_space = true

[palette]
primary = "#F11A7B"
secondary = "#f5c2e7"
accent = "#F86F03"
overlay = "#7f3515"
white = "#FCF5ED"
black = "#072541"

[transient_prompt]
background = "transparant"
foreground  = "p:secondary"
template    = "❯ "

[secondary_prompt]
background = "transparent"
foreground = "p:secondary"
template = " "

[[blocks]]
type	    = "prompt"
alignment   = "left"
newline	    = true

    [[blocks.segments]]
	type	    = "os"
	style	    = "diamond"
	trailing_diamond = ""
	foreground  = "p:white"
	background  = "p:primary"
	template    = " {{ .UserName }} {{ .Icon }} "

    [[blocks.segments]]
	type	    = "path"
	style	    = "plain"
	foreground  = "p:primary"

	[blocks.segments.properties]
	    style   = "full"
    
    [[blocks.segments]]
	type	= "git"
	style	= "plain"
	foreground = "p:secondary"

	[blocks.segments.properties]
	fetch_status = true
	branch_icon = "󰊢 "

[[blocks]]
type	    = "prompt"
alignment   = "right"
overflow    = "hidden"

    [[blocks.segments]]
	type	= "executiontime"
	style	= "plain"
	foreground = "p:accent"
	template = " {{ .FormattedMs }} "

	[blocks.segments.properties]
	threshold	= 500
	style		= "austin"

    [[blocks.segments]]
	type = "deno"
	style = "plain"
	foreground = "p:accent"
	template = "  "

    [[blocks.segments]]
	type = "php"
	style = "plain"
	template = " "

    [[blocks.segments]]
	type	    = "time"
	style	    = "plain"
	foreground  = "p:accent"

	[blocks.segments.properties]
	time_format = "15:04:05"	


[[blocks]]
type	    = "prompt"
alignment   = "left"
newline	    = true

    [[blocks.segments]]
	type	    = "text"
	style	    = "plain"
	foreground  = "p:primary"
	template    = "❯"


