# preload = $HOME/.config/hypr/assets/wallpaper.png
# wallpaper = ,$HOME/.config/hypr/assets/wallpaper.png
splash = false
ipc=off

wallpaper {
    monitor = 
    path = $HOME/.config/hypr/assets/hello-world-computer-neon.png
    fit_mode = cover
}
